version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: athletics_postgres
    environment:
      POSTGRES_DB: athletics_dw
      POSTGRES_USER: athletics_user
      POSTGRES_PASSWORD: athletics_pass123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    restart: unless-stopped
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: athletics_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@athletics.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: